In [ ]:
import numpy as np
# Set random seed for reproducibility
np.random.seed(42)

#Introduction
## Manual Backpropagation in Multi-Layer Perceptron (MLP)

## Learning Objectives:
- Understand forward propagation step-by-step
- Derive and compute gradients manually using backpropagation
- See how weights are updated using gradient descent
- Verify that the loss decreases after one training iteration

## Network Architecture:
- **Input Layer**: 2 neurons
- **Hidden Layer**: 3 neurons (with sigmoid activation)
- **Output Layer**: 1 neuron (with sigmoid activation)

## Loss Function:
Mean Squared Error (MSE): $L = \frac{1}{2}(y - \hat{y})^2$

---

#STEP 1: Network Initialization
We initialize our network with:
- **Weights (W)**: Random small values (using normal distribution)
- **Biases (b)**: Zeros

## Weight Matrices:
- $W_1$: Shape (2, 3) - connects input layer to hidden layer
- $b_1$: Shape (1, 3) - bias for hidden layer
- $W_2$: Shape (3, 1) - connects hidden layer to output layer
- $b_2$: Shape (1, 1) - bias for output layer

**Why small random weights?**
- Breaks symmetry (all neurons learn different features)
- Prevents vanishing/exploding gradients initially

In [ ]:
# ============================================
# STEP 1: Initialize Network Architecture
# ============================================
# Simple network: 2 inputs -> 3 hidden neurons -> 1 output
# Architecture: [2, 3, 1]

input_size = 2
hidden_size = 3
output_size = 1

# Initialize weights and biases with small random values
W1 = np.random.randn(input_size, hidden_size) * 0.5  # Shape: (2, 3)
b1 = np.zeros((1, hidden_size))                       # Shape: (1, 3)

W2 = np.random.randn(hidden_size, output_size) * 0.5  # Shape: (3, 1)
b2 = np.zeros((1, output_size))                       # Shape: (1, 1)

print("="*60)
print("INITIAL WEIGHTS AND BIASES")
print("="*60)
print(f"W1 (Input to Hidden):\n{W1}\n")
print(f"b1 (Hidden bias):\n{b1}\n")
print(f"W2 (Hidden to Output):\n{W2}\n")
print(f"b2 (Output bias):\n{b2}\n")

INITIAL WEIGHTS AND BIASES
W1 (Input to Hidden):
[[ 0.24835708 -0.06913215  0.32384427]
 [ 0.76151493 -0.11707669 -0.11706848]]

b1 (Hidden bias):
[[0. 0. 0.]]

W2 (Hidden to Output):
[[ 0.78960641]
 [ 0.38371736]
 [-0.23473719]]

b2 (Output bias):
[[0.]]



# Step 2: Define Activation Functions

## Sigmoid Function:
$$\sigma(x) = \frac{1}{1 + e^{-x}}$$

**Properties:**
- Output range: (0, 1)
- Smooth and differentiable
- Used for binary classification

## Sigmoid Derivative:
$$\sigma'(x) = \sigma(x) \cdot (1 - \sigma(x))$$

**Why this form?**
- Computationally efficient
- Uses the already computed sigmoid value
- No need to recompute exponentials

**Key Insight**: We'll use this derivative during backpropagation!

In [ ]:
# ============================================
# STEP 2: Define Activation Functions
# ============================================
def sigmoid(x):
    """Sigmoid activation function"""
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    """Derivative of sigmoid function"""
    return x * (1 - x)

# Step 3: Prepare Training Data

We'll use **one training example** to see each calculation clearly.

## Training Example:
- **Input (X)**: [0.5, 0.8] - two features
- **Target (y)**: [0.7] - desired output

**Shape notation:**
- X: (1, 2) means 1 sample with 2 features
- y: (1, 1) means 1 sample with 1 output value

In a real scenario, you'd have multiple samples, but we start with one to understand the mathematics clearly.

In [ ]:
# ============================================
# STEP 3: Sample Training Data
# ============================================
# Single training example for detailed demonstration
X = np.array([[0.5, 0.8]])  # Shape: (1, 2) - one sample, two features
y = np.array([[0.7]])        # Shape: (1, 1) - target output

print("="*60)
print("TRAINING DATA")
print("="*60)
print(f"Input (X): {X}")
print(f"Target (y): {y}\n")

TRAINING DATA
Input (X): [[0.5 0.8]]
Target (y): [[0.7]]



# Step 4: Forward Propagation

Forward propagation passes input through the network to get output.

## Hidden Layer Computation:

### Step 4.1: Linear Combination
$$z_1 = X \cdot W_1 + b_1$$

**What's happening?**
- Each hidden neuron receives weighted sum of inputs
- Matrix multiplication: $(1, 2) \times (2, 3) = (1, 3)$
- Result: 3 values (one for each hidden neuron)

### Step 4.2: Apply Activation
$$a_1 = \sigma(z_1)$$

**What's happening?**
- Apply sigmoid to each value in $z_1$
- Introduces non-linearity (essential for learning complex patterns)
- Output: activated hidden layer values

## Output Layer Computation:

### Step 4.3: Linear Combination
$$z_2 = a_1 \cdot W_2 + b_2$$

**What's happening?**
- Hidden layer outputs ($a_1$) are inputs to output layer
- Matrix multiplication: $(1, 3) \times (3, 1) = (1, 1)$
- Result: 1 value (final prediction before activation)

### Step 4.4: Apply Activation
$$a_2 = \sigma(z_2)$$

**This is our prediction!** $\hat{y} = a_2$

### Step 4.5: Calculate Loss
$$L = \frac{1}{2}(y - a_2)^2$$

**Mean Squared Error (MSE)**
- Measures how far our prediction is from the target
- Factor of $\frac{1}{2}$ simplifies derivative
- Goal: Minimize this loss!

In [ ]:
# ============================================
# STEP 4: FORWARD PROPAGATION (Step-by-Step)
# ============================================
print("="*60)
print("FORWARD PROPAGATION")
print("="*60)

# Hidden layer calculations
z1 = np.dot(X, W1) + b1  # Linear combination: z1 = X * W1 + b1
print(f"Step 1 - Hidden layer linear output (z1):")
print(f"  z1 = X · W1 + b1")
print(f"  z1 = {z1}\n")

a1 = sigmoid(z1)  # Activation: a1 = sigmoid(z1)
print(f"Step 2 - Hidden layer activation (a1):")
print(f"  a1 = sigmoid(z1)")
print(f"  a1 = {a1}\n")

# Output layer calculations
z2 = np.dot(a1, W2) + b2  # Linear combination: z2 = a1 * W2 + b2
print(f"Step 3 - Output layer linear output (z2):")
print(f"  z2 = a1 · W2 + b2")
print(f"  z2 = {z2}\n")

a2 = sigmoid(z2)  # Final output: a2 = sigmoid(z2)
print(f"Step 4 - Final output (a2):")
print(f"  a2 = sigmoid(z2)")
print(f"  a2 = {a2}\n")

# Calculate loss (Mean Squared Error)
loss = 0.5 * np.sum((y - a2)**2)
print(f"Step 5 - Loss (MSE):")
print(f"  Loss = 0.5 * (y - a2)²")
print(f"  Loss = {loss}\n")

FORWARD PROPAGATION
Step 1 - Hidden layer linear output (z1):
  z1 = X · W1 + b1
  z1 = [[ 0.73339048 -0.12822743  0.06826735]]

Step 2 - Hidden layer activation (a1):
  a1 = sigmoid(z1)
  a1 = [[0.67554885 0.467987   0.51706021]]

Step 3 - Output layer linear output (z2):
  z2 = a1 · W2 + b2
  z2 = [[0.59161917]]

Step 4 - Final output (a2):
  a2 = sigmoid(z2)
  a2 = [[0.64373657]]

Step 5 - Loss (MSE):
  Loss = 0.5 * (y - a2)²
  Loss = 0.0015827866106417003



# Step 5: Backpropagation - Output Layer

**Goal**: Calculate gradients (how much each weight contributed to the error)

## Chain Rule Reminder:
$$\frac{\partial L}{\partial W} = \frac{\partial L}{\partial a} \cdot \frac{\partial a}{\partial z} \cdot \frac{\partial z}{\partial W}$$

## Output Layer Gradients:

### Step 5.1: Calculate Output Error
$$\text{error}_{\text{output}} = a_2 - y$$

**Derivative of loss with respect to output:**
$$\frac{\partial L}{\partial a_2} = a_2 - y$$

### Step 5.2: Calculate Output Delta
$$\delta_2 = \text{error}_{\text{output}} \cdot \sigma'(a_2)$$

**This is the chain rule!**
- $\frac{\partial L}{\partial a_2}$: error
- $\frac{\partial a_2}{\partial z_2}$: sigmoid derivative

### Step 5.3: Calculate Gradient for W2
$$\frac{\partial L}{\partial W_2} = a_1^T \cdot \delta_2$$

**Why transpose?** Matrix dimensions must match for multiplication.

### Step 5.4: Calculate Gradient for b2
$$\frac{\partial L}{\partial b_2} = \sum \delta_2$$

**Why sum?** Bias affects all samples equally.

# Step 5: Backpropagation -(Hidden Layer)

Now we propagate the error backwards to the hidden layer.

## Hidden Layer Gradients:

### Step 5.5: Backpropagate Error to Hidden Layer
$$\text{error}_{\text{hidden}} = \delta_2 \cdot W_2^T$$

**What's happening?**
- Error flows backward through weights
- Each hidden neuron gets proportional error based on its contribution
- Matrix multiplication: $(1, 1) \times (1, 3) = (1, 3)$

### Step 5.6: Calculate Hidden Delta
$$\delta_1 = \text{error}_{\text{hidden}} \cdot \sigma'(a_1)$$

**Again, the chain rule!**
- Multiply by derivative of activation

### Step 5.7: Calculate Gradient for W1
$$\frac{\partial L}{\partial W_1} = X^T \cdot \delta_1$$

### Step 5.8: Calculate Gradient for b1
$$\frac{\partial L}{\partial b_1} = \sum \delta_1$$

**Key Insight**: Backpropagation systematically applies the chain rule from output to input!

In [ ]:
# ============================================
# STEP 5: BACKPROPAGATION (Step-by-Step)
# ============================================
print("="*60)
print("BACKPROPAGATION - GRADIENT COMPUTATION")
print("="*60)

# OUTPUT LAYER GRADIENTS
# ----------------------
print("\n--- OUTPUT LAYER GRADIENTS ---\n")

# Step 1: Calculate error at output
error_output = a2 - y  # Error = prediction - target
print(f"Step 1 - Output error:")
print(f"  error_output = a2 - y")
print(f"  error_output = {error_output}\n")

# Step 2: Calculate delta for output layer
# delta_output = error * derivative of activation
delta_output = error_output * sigmoid_derivative(a2)
print(f"Step 2 - Output layer delta:")
print(f"  delta_output = error_output * sigmoid'(a2)")
print(f"  delta_output = {error_output} * {sigmoid_derivative(a2)}")
print(f"  delta_output = {delta_output}\n")

# Step 3: Calculate gradients for W2 and b2
dW2 = np.dot(a1.T, delta_output)  # Gradient for W2
db2 = np.sum(delta_output, axis=0, keepdims=True)  # Gradient for b2

print(f"Step 3 - Gradient for W2:")
print(f"  dW2 = a1ᵀ · delta_output")
print(f"  dW2 = {dW2}\n")

print(f"Step 4 - Gradient for b2:")
print(f"  db2 = sum(delta_output)")
print(f"  db2 = {db2}\n")

BACKPROPAGATION - GRADIENT COMPUTATION

--- OUTPUT LAYER GRADIENTS ---

Step 1 - Output error:
  error_output = a2 - y
  error_output = [[-0.05626343]]

Step 2 - Output layer delta:
  delta_output = error_output * sigmoid'(a2)
  delta_output = [[-0.05626343]] * [[0.2293398]]
  delta_output = [[-0.01290344]]

Step 3 - Gradient for W2:
  dW2 = a1ᵀ · delta_output
  dW2 = [[-0.00871691]
 [-0.00603864]
 [-0.00667186]]

Step 4 - Gradient for b2:
  db2 = sum(delta_output)
  db2 = [[-0.01290344]]



# Step 6: Update Weights Using Gradient Descent

Now we use the computed gradients to update our weights!

## Gradient Descent Update Rule:
$$W_{\text{new}} = W_{\text{old}} - \alpha \cdot \frac{\partial L}{\partial W}$$

Where:
- $\alpha$ = learning rate (how big a step we take)
- $\frac{\partial L}{\partial W}$ = gradient (direction of steepest increase)
- We subtract because we want to minimize loss

## Learning Rate:
- Too large: Might overshoot the minimum
- Too small: Learning is very slow
- We use $\alpha = 0.1$ for this example

**Key Intuition**:
- Positive gradient → weight increased loss → decrease weight
- Negative gradient → weight decreased loss → increase weight

In [ ]:
# HIDDEN LAYER GRADIENTS
# ----------------------
print("--- HIDDEN LAYER GRADIENTS ---\n")

# Step 5: Backpropagate error to hidden layer
error_hidden = np.dot(delta_output, W2.T)
print(f"Step 5 - Hidden layer error:")
print(f"  error_hidden = delta_output · W2ᵀ")
print(f"  error_hidden = {error_hidden}\n")

# Step 6: Calculate delta for hidden layer
delta_hidden = error_hidden * sigmoid_derivative(a1)
print(f"Step 6 - Hidden layer delta:")
print(f"  delta_hidden = error_hidden * sigmoid'(a1)")
print(f"  delta_hidden = {delta_hidden}\n")

# Step 7: Calculate gradients for W1 and b1
dW1 = np.dot(X.T, delta_hidden)  # Gradient for W1
db1 = np.sum(delta_hidden, axis=0, keepdims=True)  # Gradient for b1

print(f"Step 7 - Gradient for W1:")
print(f"  dW1 = Xᵀ · delta_hidden")
print(f"  dW1 = {dW1}\n")

print(f"Step 8 - Gradient for b1:")
print(f"  db1 = sum(delta_hidden)")
print(f"  db1 = {db1}\n")

--- HIDDEN LAYER GRADIENTS ---

Step 5 - Hidden layer error:
  error_hidden = delta_output · W2ᵀ
  error_hidden = [[-0.01018864 -0.00495128  0.00302892]]

Step 6 - Hidden layer delta:
  delta_hidden = error_hidden * sigmoid'(a1)
  delta_hidden = [[-0.00223317 -0.00123274  0.00075635]]

Step 7 - Gradient for W1:
  dW1 = Xᵀ · delta_hidden
  dW1 = [[-0.00111659 -0.00061637  0.00037817]
 [-0.00178654 -0.0009862   0.00060508]]

Step 8 - Gradient for b1:
  db1 = sum(delta_hidden)
  db1 = [[-0.00223317 -0.00123274  0.00075635]]



In [ ]:
# ============================================
# STEP 6: GRADIENT DESCENT UPDATE
# ============================================
print("="*60)
print("GRADIENT DESCENT - WEIGHT UPDATE")
print("="*60)

learning_rate = 0.1
print(f"Learning rate: {learning_rate}\n")

# Update weights and biases
W2_new = W2 - learning_rate * dW2
b2_new = b2 - learning_rate * db2
W1_new = W1 - learning_rate * dW1
b1_new = b1 - learning_rate * db1

print("Weight updates:")
print(f"  W2_new = W2 - lr * dW2")
print(f"  W2: {W2.flatten()} -> {W2_new.flatten()}\n")

print(f"  b2_new = b2 - lr * db2")
print(f"  b2: {b2.flatten()} -> {b2_new.flatten()}\n")

print(f"  W1_new = W1 - lr * dW1\n{W1_new}\n")

print(f"  b1_new = b1 - lr * db1")
print(f"  b1: {b1.flatten()} -> {b1_new.flatten()}\n")

GRADIENT DESCENT - WEIGHT UPDATE
Learning rate: 0.1

Weight updates:
  W2_new = W2 - lr * dW2
  W2: [ 0.78960641  0.38371736 -0.23473719] -> [ 0.7904781   0.38432123 -0.23407001]

  b2_new = b2 - lr * db2
  b2: [0.] -> [0.00129034]

  W1_new = W1 - lr * dW1
[[ 0.24846874 -0.06907051  0.32380645]
 [ 0.76169358 -0.11697807 -0.11712899]]

  b1_new = b1 - lr * db1
  b1: [0. 0. 0.] -> [ 2.23317290e-04  1.23274455e-04 -7.56347926e-05]



# Step 7: Verify That Learning Happened!

Let's do another forward pass with updated weights and check if loss decreased.

## Expected Result:
Loss should be **smaller** than before

If loss decreased:
- Gradients were computed correctly
- Weights moved in the right direction
- Network is learning!

## Why Loss Must Decrease (for one sample):
- Gradient descent moves weights in the direction that reduces loss
- With proper learning rate, loss should decrease
- If loss increases, something is wrong (gradient bug or learning rate too high)

In [ ]:
# ============================================
# STEP 7: VERIFY WITH UPDATED WEIGHTS
# ============================================
print("="*60)
print("VERIFICATION - FORWARD PASS WITH UPDATED WEIGHTS")
print("="*60)

# Forward pass with new weights
z1_new = np.dot(X, W1_new) + b1_new
a1_new = sigmoid(z1_new)
z2_new = np.dot(a1_new, W2_new) + b2_new
a2_new = sigmoid(z2_new)
loss_new = 0.5 * np.sum((y - a2_new)**2)

print(f"Old output: {a2.flatten()}")
print(f"New output: {a2_new.flatten()}")
print(f"\nOld loss: {loss:.6f}")
print(f"New loss: {loss_new:.6f}")
print(f"Loss reduction: {loss - loss_new:.6f}")

print("\n" + "="*60)
print("Backpropagation successful! Loss decreased ✓")
print("="*60)

VERIFICATION - FORWARD PASS WITH UPDATED WEIGHTS
Old output: [0.64373657]
New output: [0.64433505]

Old loss: 0.001583
New loss: 0.001549
Loss reduction: 0.000033

Backpropagation successful! Loss decreased ✓


**Practice Exercises:**
1. Change learning rate to 0.5 and 0.01 - observe the effect
2. Add more hidden neurons and see how gradients change
3. Try different activation functions (ReLU, tanh)
4. Implement multiple training iterations (epochs)
5. Calculate gradients manually for one neuron to verify